# ???
spring.application.name=user-practice
# ????
server.port=8080

# ========== ??????????????itcast?? ==========
# ??????itcast????????
spring.datasource.url=jdbc:mysql://localhost:3306/itcast?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
# ????????root???????
spring.datasource.username=root
# ??MySQL???????????
spring.datasource.password=123456
# ???
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== MyBatis-Plus?? ==========
# ??????????????????????????????
mybatis-plus.configuration.map-underscore-to-camel-case=true
# ?????SQL??????
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
